import type { WatercolorScene } from "./types";

export const heroScene: WatercolorScene = {
  name: "hero",
  background: "ivory",
  washes: [
    {
      shape: "bloom",
      color: "coral",
      x: "8%",
      y: "12%",
      size: 480,
      blur: 58,
      opacity: 0.3,
      rotation: -22,
    },
    {
      shape: "ribbon",
      color: "rose",
      x: "22%",
      y: "28%",
      size: 520,
      blur: 68,
      opacity: 0.27,
      rotation: -12,
    },
    {
      shape: "petal",
      color: "peach",
      x: "38%",
      y: "18%",
      size: 440,
      blur: 62,
      opacity: 0.26,
      rotation: 8,
    },
    {
      shape: "drift",
      color: "buttercream",
      x: "52%",
      y: "35%",
      size: 500,
      blur: 72,
      opacity: 0.25,
      rotation: -5,
    },
    {
      shape: "cloud",
      color: "mint",
      x: "65%",
      y: "22%",
      size: 460,
      blur: 65,
      opacity: 0.26,
      rotation: 15,
    },
    {
      shape: "pool",
      color: "sage",
      x: "78%",
      y: "38%",
      size: 420,
      blur: 78,
      opacity: 0.24,
      rotation: -8,
    },
    {
      shape: "bloom",
      color: "sky",
      x: "88%",
      y: "18%",
      size: 400,
      blur: 68,
      opacity: 0.27,
      rotation: 20,
    },
    {
      shape: "ribbon",
      color: "mist",
      x: "18%",
      y: "72%",
      size: 480,
      blur: 82,
      opacity: 0.24,
      rotation: 10,
    },
    {
      shape: "drift",
      color: "periwinkle",
      x: "42%",
      y: "78%",
      size: 520,
      blur: 88,
      opacity: 0.23,
      rotation: -15,
    },
    {
      shape: "petal",
      color: "lavender",
      x: "68%",
      y: "70%",
      size: 450,
      blur: 78,
      opacity: 0.25,
      rotation: 6,
    },
    {
      shape: "cloud",
      color: "lilac",
      x: "85%",
      y: "82%",
      size: 430,
      blur: 85,
      opacity: 0.24,
      rotation: -18,
    },
  ],
};

export const storyScene: WatercolorScene = {
  name: "story",
  background: "ivory",
  washes: [
    {
      shape: "drift",
      color: "peach",
      x: "10%",
      y: "30%",
      size: 380,
      blur: 85,
      opacity: 0.14,
      rotation: -10,
    },
    {
      shape: "cloud",
      color: "mint",
      x: "85%",
      y: "25%",
      size: 360,
      blur: 92,
      opacity: 0.13,
      rotation: 12,
    },
    {
      shape: "pool",
      color: "periwinkle",
      x: "50%",
      y: "80%",
      size: 400,
      blur: 100,
      opacity: 0.12,
      rotation: -5,
    },
  ],
};
